### ISSUE TITLE
Filter Tool: add "filter" and "lightweight" functionality

### ISSUE THREAD

**Issue by nickcounts** [nickcounts/MDRT#41]
The FD Filter Tool has options for "Filter data" and "Make lightweight"

We need to implement this functionality.

### Filter Data:
Allow attenuation of specific frequencies (high-pass, low-pass, band-pass, etc.)
- This would be some signals processing math
- Writing the Matlab functions to do the math
- Integrating it with the existing GUI

### Make Lightweight:
Generate decimated data streams for easier plotting and analysis. some of our data is _significantly_ more dense (higher sample rate) than we ever need. This would allow automatically reducing the number of data points while retaining the shape and character of the data.
- Automatic decimation to a user-specified maximum sample rate for the entire stream
- Optional: allow the user to select a region that retains the maximum resolution while decimating the remaining data
- Optional: automatically detect "interesting regions" to retain maximum resolution and decimate the remaining data

**Comment by jtsingh7** [comment]
pretty much all finished, just still trying to get the databrush lightweight option to work
