### ISSUE TITLE
filterFdTool error when loading small data file

### ISSUE THREAD

**Issue by nickcounts** [nickcounts/MDRT#42]
When loading a small but valid FD file sometimes you get:

> Error using tsmovavg>simplema (line 228)
> Lag must be scalar greater than 0 or less than the number of observations.
> 
> Error in tsmovavg (line 95)
>         vout = simplema(vin, lag, vinVars, observ);
> 
> Error in filterFdTool/applySmoothing (line 425)
>         smoothData = tsmovavg(weighted,'s',window_size,1);
> 
> Error in filterFdTool/updateSmoothedCurve (line 431)
>         hs.hLine2.YData = applySmoothing(fd.ts);
> 
> Error in filterFdTool/loadDataFile (line 522)
>         updateSmoothedCurve;
> 
> Error in filterFdTool (line 78)
>                 loadDataFile();
> 
> Error in review>uiButton_filterData_Callback (line 432)
> filterFdTool(fdFullFileName);
> 
> 
> Error in gui_mainfcn (line 95)
>         feval(varargin{:});
> 
> Error in review (line 48)
>     gui_mainfcn(gui_State, varargin{:});
> 
> 
> Error in
> @(hObject,eventdata)review('uiButton_filterData_Callback',hObject,eventdata,guidata(hObject))
> 
>  
> Error while evaluating UIControl Callback

I think we need to add some kind of size error checking for the default filter parameters

**Comment by jtsingh7** [comment]
I think this should work now...? What kind of file size was causing problems

**Comment by nickcounts** [comment]
If the default window size was bigger than the total number of points in the original signal I think it would crash. 

It might need some error checking to fix - either force a usable window if the size is too small, or do a try-catch to handle any exceptions and let the user adjust the window size?

**Comment by jtsingh7** [comment]
new algorithm automatically reduces window size when necessary. Tested and shouldn't run into this issue anymore
