### ISSUE TITLE
FilterFdTool: Toolbox Dependency

### ISSUE THREAD

**Issue by nickcounts** [nickcounts/MDRT#44]
The `filterFDtool()` is dependent on a paid toolbox. Refactor to remove dependency for maximum portability

**Comment by jtsingh7** [comment]
To remove dependency on Financial/Signal Processing toolboxes, current solution is to replace the weighted Gaussian/tsmovavg method with moving "box" average, which should actually do a better job of noise reduction. Process: extract 'data' and 'time' from the FD time series and put in new arrays, use movmean() method on data array (box size determined by user), create new timeseries with averaged data array and original time array, plot new time series against original. Need to integrate with existing GUI/code

**Comment by nickcounts** [comment]
Seems like a good solution outline. Note that `movemean()` wasn't implemented until r2016a.  R2014b compatibility would be ideal, but not required.

It might be a good exercise to write your own `movemean()` that accepts our FD structure as an argument.

Thoughts?

**Comment by jtsingh7** [comment]
interesting, didn't know that. Working on a homemade "movmean" method now

**Comment by jtsingh7** [comment]
replaced instances of paid toolbox functions with custom methods.
